### ISSUE TITLE
FFMPEG not found.

### ISSUE THREAD

**Issue by TGKitten** [helionmusic/rhinobot_heroku#11]
So when starting up the bot on heroku I do the play command and FFMPEG is not found.

Error: (**HasteBin link at the end of code**)

```2018-12-31T20:16:03.596003+00:00 heroku[worker.1]: Starting process with command `python run.py`
2018-12-31T20:16:04.238752+00:00 heroku[worker.1]: State changed from starting to up
2018-12-31T20:16:06.211213+00:00 app[worker.1]: [INFO] launcher: Starting sanity checks
2018-12-31T20:16:06.211405+00:00 app[worker.1]: [INFO] launcher: Checking for Python 3.5+
2018-12-31T20:16:06.211581+00:00 app[worker.1]: [INFO] launcher: Checking console encoding
2018-12-31T20:16:06.211760+00:00 app[worker.1]: [INFO] launcher: Ensuring we're in the right environment
2018-12-31T20:16:08.573814+00:00 app[worker.1]: [INFO] launcher: Required checks passed.
2018-12-31T20:16:08.574304+00:00 app[worker.1]: [INFO] launcher: Optional checks passed.
2018-12-31T20:16:11.191347+00:00 app[worker.1]: ]2;MusicBot 1.9.8_1
2018-12-31T20:16:11.222313+00:00 app[worker.1]: [37mStarting MusicBot 1.9.8_1[0m
2018-12-31T20:16:11.222688+00:00 app[worker.1]: [37mLoaded autoplaylist with 2531 entries[0m
2018-12-31T20:16:13.792330+00:00 app[worker.1]: 
2018-12-31T20:16:13.846502+00:00 app[worker.1]: [37mConnected: 529386594239643668/Hello!#2133[0m
2018-12-31T20:16:13.848197+00:00 app[worker.1]: [37mOwner:     384262994345066506/LowTek#0001
2018-12-31T20:16:13.848311+00:00 app[worker.1]: [0m
2018-12-31T20:16:13.849186+00:00 app[worker.1]: [37mGuild List:[0m
2018-12-31T20:16:13.850595+00:00 app[worker.1]: [37m - Fusion A Testing[0m
2018-12-31T20:16:13.850799+00:00 app[worker.1]: 
2018-12-31T20:16:13.852357+00:00 app[worker.1]: [37mNot bound to any text channels[0m
2018-12-31T20:16:13.853178+00:00 app[worker.1]: [37mNot autojoining any voice channels[0m
2018-12-31T20:16:13.853256+00:00 app[worker.1]: 
2018-12-31T20:16:13.853903+00:00 app[worker.1]: [37mFound resumable voice channel Fusion A Testing/2[0m
2018-12-31T20:16:13.854594+00:00 app[worker.1]: [37mFound owner in "2"[0m
2018-12-31T20:16:13.855089+00:00 app[worker.1]: [37mAttempting to join Fusion A Testing/2[0m
2018-12-31T20:16:14.865361+00:00 app[worker.1]: [37mJoined Fusion A Testing/2[0m
2018-12-31T20:16:19.462076+00:00 app[worker.1]: [37mDownload started: https://youtube.com/watch?v=NSPv6Fa0cyY[0m
2018-12-31T20:16:20.687398+00:00 app[worker.1]: [37mDownload complete: https://youtube.com/watch?v=NSPv6Fa0cyY[0m
2018-12-31T20:16:21.479299+00:00 app[worker.1]: Task exception was never retrieved
2018-12-31T20:16:21.479311+00:00 app[worker.1]: future: <Task finished coro=<MusicPlayer._play() done, defined at /app/musicbot/player.py:242> exception=ClientException('ffmpeg was not found.')>
2018-12-31T20:16:21.479313+00:00 app[worker.1]: Traceback (most recent call last):
2018-12-31T20:16:21.479318+00:00 app[worker.1]:   File "/app/musicbot/player.py", line 283, in _play
2018-12-31T20:16:21.479320+00:00 app[worker.1]:     stderr=subprocess.PIPE
2018-12-31T20:16:21.479322+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/player.py", line 164, in __init__
2018-12-31T20:16:21.479323+00:00 app[worker.1]:     raise ClientException(executable + ' was not found.') from None
2018-12-31T20:16:21.483660+00:00 app[worker.1]: discord.errors.ClientException: ffmpeg was not found.```

HasteBin version : https://hastebin.com/idudineyos.makefile

**Comment by TGKitten** [comment]
> you can fix this by adding the [ffmpeg buildpack](https://elements.heroku.com/buildpacks/jonathanong/heroku-buildpack-ffmpeg-latest) on your heroku app

Still not working same problem

**Comment by helionmusic** [comment]
Issue is fixed now from PR #17 
Let me know if you're still having trouble with this
