### ISSUE TITLE
I get the following logs when I try to start the bot. 

### ISSUE THREAD

**Issue by TheFatalKiller** [helionmusic/rhinobot_heroku#23]
**Describe the problem**
I get the following logs/errors when I try to turn my bot online. 

2019-07-04T23:50:21.426978+00:00 app[worker.1]: [ERROR] launcher: Error starting bot
2019-07-04T23:50:21.426996+00:00 app[worker.1]: Traceback (most recent call last):
2019-07-04T23:50:21.427000+00:00 app[worker.1]:   File "run.py", line 367, in main
2019-07-04T23:50:21.427002+00:00 app[worker.1]:     from musicbot import MusicBot
2019-07-04T23:50:21.427005+00:00 app[worker.1]:   File "/app/musicbot/__init__.py", line 74, in <module>
2019-07-04T23:50:21.427008+00:00 app[worker.1]:     from .bot import MusicBot
2019-07-04T23:50:21.427010+00:00 app[worker.1]:   File "/app/musicbot/bot.py", line 46, in <module>
2019-07-04T23:50:21.427012+00:00 app[worker.1]:     load_opus_lib()
2019-07-04T23:50:21.427014+00:00 app[worker.1]:   File "/app/musicbot/opus_loader.py", line 17, in load_opus_lib
2019-07-04T23:50:21.427017+00:00 app[worker.1]:     raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
2019-07-04T23:50:21.427019+00:00 app[worker.1]: RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
2019-07-04T23:50:21.427295+00:00 app[worker.1]: 
2019-07-04T23:50:21.427300+00:00 app[worker.1]: [INFO] launcher: All done.

**Have you followed all the instructions?**
Yes

**Tried updating the dependencies?**
??

**Bot version**
Im using the latest commit which is:
Merge pull request #22 from codeinteger6/master
committed by codeinteger6 ⋅ 550661c7

**Comment by codeinteger6** [comment]
Hi just checking in, as you closed the issue, is the bot working now?

**Comment by TheFatalKiller** [comment]
Working just fine, thank you for checking and keep up the great work!

**Comment by codeinteger6** [comment]
No problem, enjoy 🙂
