### ISSUE TITLE
i tried to make a second bot with the exact same steps

### ISSUE THREAD

**Issue by BlazeDraaws** [helionmusic/rhinobot_heroku#34]
**Describe the problem** I did the exact same steps but this time it isnt showing up as online
**Have you followed all the instructions?** 
- [X] Yes, I followed the instructions properly.

**Tried updating the dependencies?** 
- [X] Yes, they are up to date.
- [ ] Not applicable for this issue.

the log:
2019-08-15T19:25:31.323550+00:00 app[worker.1]: [INFO] launcher: Ensuring we're in the right environment
2019-08-15T19:25:32.253919+00:00 app[worker.1]: [INFO] launcher: Required checks passed.
2019-08-15T19:25:32.254206+00:00 app[worker.1]: [INFO] launcher: Optional checks passed.
2019-08-15T19:25:34.037557+00:00 app[worker.1]: ]2;MusicBot release-120519
2019-08-15T19:25:34.047124+00:00 app[worker.1]: [ERROR] launcher: Error starting bot
2019-08-15T19:25:34.047128+00:00 app[worker.1]: Traceback (most recent call last):
2019-08-15T19:25:34.047130+00:00 app[worker.1]:   File "run.py", line 368, in main
2019-08-15T19:25:34.047132+00:00 app[worker.1]:     m = MusicBot()
2019-08-15T19:25:34.047135+00:00 app[worker.1]:   File "/app/musicbot/bot.py", line 79, in __init__
2019-08-15T19:25:34.047137+00:00 app[worker.1]:     self.permissions = Permissions(perms_file, grant_all=[self.config.owner_id])
2019-08-15T19:25:34.047139+00:00 app[worker.1]:   File "/app/musicbot/permissions.py", line 77, in __init__
2019-08-15T19:25:34.047141+00:00 app[worker.1]:     self.groups.add(PermissionGroup(section, self.config[section]))
2019-08-15T19:25:34.047143+00:00 app[worker.1]:   File "/app/musicbot/permissions.py", line 149, in __init__
2019-08-15T19:25:34.047145+00:00 app[worker.1]:     self.instaskip = section_data.getboolean('InstaSkip', fallback=fallback.InstaSkip)
2019-08-15T19:25:34.047147+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/configparser.py", line 1301, in get
2019-08-15T19:25:34.047149+00:00 app[worker.1]:     fallback=fallback, **kwargs)
2019-08-15T19:25:34.047151+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/configparser.py", line 828, in getboolean
2019-08-15T19:25:34.047153+00:00 app[worker.1]:     raw=raw, vars=vars, fallback=fallback, **kwargs)
2019-08-15T19:25:34.047155+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/configparser.py", line 808, in _get_conv
2019-08-15T19:25:34.047158+00:00 app[worker.1]:     **kwargs)
2019-08-15T19:25:34.047160+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/configparser.py", line 802, in _get
2019-08-15T19:25:34.047162+00:00 app[worker.1]:     return conv(self.get(section, option, **kwargs))
2019-08-15T19:25:34.047164+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/configparser.py", line 1160, in _convert_to_boolean
2019-08-15T19:25:34.047166+00:00 app[worker.1]:     raise ValueError('Not a boolean: %s' % value)
2019-08-15T19:25:34.047168+00:00 app[worker.1]: ValueError: Not a boolean: np
2019-08-15T19:25:34.047235+00:00 app[worker.1]:

**Comment by codeinteger6** [comment]
I'm not sure, but your options.ini and/or permissions.ini file may have been set incorrectly. I would try repeating the deploy process again if I were you, just to make sure nothing was left out.
