### ISSUE TITLE
disconnect

### ISSUE THREAD

**Issue by Accountforthings** [helionmusic/rhinobot_heroku#5]
when i use the disconnect command, the bot does not leave the channel but when i do a play command it says its not in the channel

**Comment by Musicbotaccount** [comment]
2018-01-22T23:27:13.974413+00:00 app[worker.1]: [31m[ERROR:bot] Exception in on_message
2018-01-22T23:27:13.974417+00:00 app[worker.1]: Traceback (most recent call last):
2018-01-22T23:27:13.974418+00:00 app[worker.1]:   File "/app/musicbot/bot.py", line 2496, in on_message
2018-01-22T23:27:13.974419+00:00 app[worker.1]:     response = await handler(**handler_kwargs)
2018-01-22T23:27:13.974419+00:00 app[worker.1]:   File "/app/musicbot/bot.py", line 2294, in cmd_disconnect
2018-01-22T23:27:13.974420+00:00 app[worker.1]:     await self.disconnect_voice_client(server)
2018-01-22T23:27:13.974422+00:00 app[worker.1]:   File "/app/musicbot/bot.py", line 526, in disconnect_voice_client
2018-01-22T23:27:13.974422+00:00 app[worker.1]:     await vc.disconnect()
2018-01-22T23:27:13.974424+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/voice_client.py", line 297, in disconnect
2018-01-22T23:27:13.974425+00:00 app[worker.1]:     yield from self.ws.close()
2018-01-22T23:27:13.974426+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/websockets/protocol.py", line 396, in close
2018-01-22T23:27:13.974426+00:00 app[worker.1]:     yield from asyncio.shield(self.close_connection_task)
2018-01-22T23:27:13.974427+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/gateway.py", line 686, in close_connection
2018-01-22T23:27:13.974428+00:00 app[worker.1]:     yield from super().close_connection(force=force)
2018-01-22T23:27:13.974434+00:00 app[worker.1]: TypeError: close_connection() got an unexpected keyword argument 'force'[0m

**Comment by helionmusic** [comment]
I'm not sure about the disconnect command since I didn't write the bot myself, but I do know generally Heroku would try to keep the bot alive unless you explicitly stop the worker dyno on the Heroku dashboard.
Try to restart the bot through the Heroku interface and see if it helps. Do this by selecting the bot application, then More > Restart all dynos

**Comment by Musicbotaccount** [comment]
ok

**Comment by helionmusic** [comment]
As I've not heard any response saying the error is still available in the past two weeks, I will consider the issue closed
