### ISSUE TITLE
Bot not working: Process exited with status 0

### ISSUE THREAD

**Issue by Kedoichi** [helionmusic/rhinobot_heroku#50]
Here is the log 
2020-08-21T13:49:01.484797+00:00 heroku[worker.1]: Process exited with status 0
2020-08-21T13:49:01.525808+00:00 heroku[worker.1]: State changed from up to crashed
2020-08-21T13:49:01.528569+00:00 heroku[worker.1]: State changed from crashed to starting
2020-08-21T13:49:08.556115+00:00 heroku[worker.1]: Starting process with command `python run.py`
2020-08-21T13:49:09.326414+00:00 heroku[worker.1]: State changed from starting to up
---------------------------------------------------------------------------------------------------
full log

2020-08-21T13:49:11.328050+00:00 app[worker.1]: [INFO] launcher: Starting sanity checks
2020-08-21T13:49:11.328360+00:00 app[worker.1]: [INFO] launcher: Checking for Python 3.5+
2020-08-21T13:49:11.328576+00:00 app[worker.1]: [INFO] launcher: Checking console encoding
2020-08-21T13:49:11.328795+00:00 app[worker.1]: [INFO] launcher: Ensuring we're in the right environment
2020-08-21T13:49:12.484561+00:00 app[worker.1]: [INFO] launcher: Required checks passed.
2020-08-21T13:49:12.484819+00:00 app[worker.1]: [INFO] launcher: Optional checks passed.
2020-08-21T13:49:14.718384+00:00 app[worker.1]: [ERROR] launcher: Error starting bot
2020-08-21T13:49:14.718395+00:00 app[worker.1]: Traceback (most recent call last):
2020-08-21T13:49:14.718396+00:00 app[worker.1]:   File "run.py", line 382, in main
2020-08-21T13:49:14.718396+00:00 app[worker.1]:     from musicbot import MusicBot
2020-08-21T13:49:14.718398+00:00 app[worker.1]:   File "/app/musicbot/__init__.py", line 74, in <module>
2020-08-21T13:49:14.718399+00:00 app[worker.1]:     from .bot import MusicBot
2020-08-21T13:49:14.718400+00:00 app[worker.1]:   File "/app/musicbot/bot.py", line 31, in <module>
2020-08-21T13:49:14.718400+00:00 app[worker.1]:     from .player import MusicPlayer
2020-08-21T13:49:14.718400+00:00 app[worker.1]:   File "/app/musicbot/player.py", line 17, in <module>
2020-08-21T13:49:14.718401+00:00 app[worker.1]:     from websockets.exceptions import InvalidState
2020-08-21T13:49:14.718401+00:00 app[worker.1]: ModuleNotFoundError: No module named 'websockets'
2020-08-21T13:49:14.718549+00:00 app[worker.1]: [INFO] launcher: Attempting to install dependencies...
2020-08-21T13:49:15.673437+00:00 app[worker.1]: Requirement already up-to-date: discord.py[voice]>=1.4.0 in ./.heroku/python/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.4.1)
2020-08-21T13:49:16.188247+00:00 app[worker.1]: Collecting pip
2020-08-21T13:49:16.228553+00:00 app[worker.1]:   Downloading pip-20.2.2-py2.py3-none-any.whl (1.5 MB)
2020-08-21T13:49:17.625391+00:00 app[worker.1]: Requirement already up-to-date: youtube_dl>=2020.07.28 in ./.heroku/python/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2020.7.28)
2020-08-21T13:49:17.700962+00:00 app[worker.1]: Requirement already up-to-date: colorlog in ./.heroku/python/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (4.2.1)
2020-08-21T13:49:18.267626+00:00 app[worker.1]: Requirement already up-to-date: cffi in ./.heroku/python/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (1.14.2)
2020-08-21T13:49:18.306262+00:00 app[worker.1]: Requirement already up-to-date: chardet in ./.heroku/python/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (3.0.4)
2020-08-21T13:49:18.340204+00:00 app[worker.1]: Requirement already up-to-date: opuslib in ./.heroku/python/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (3.0.1)
2020-08-21T13:49:18.343817+00:00 app[worker.1]: Requirement already satisfied, skipping upgrade: aiohttp<3.7.0,>=3.6.0 in ./.heroku/python/lib/python3.8/site-packages (from discord.py[voice]>=1.4.0->-r requirements.txt (line 1)) (3.6.2)
2020-08-21T13:49:18.381286+00:00 app[worker.1]: Requirement already satisfied, skipping upgrade: PyNaCl==1.3.0; extra == "voice" in ./.heroku/python/lib/python3.8/site-packages (from discord.py[voice]>=1.4.0->-r requirements.txt (line 1)) (1.3.0)
2020-08-21T13:49:18.402510+00:00 app[worker.1]: Requirement already satisfied, skipping upgrade: pycparser in ./.heroku/python/lib/python3.8/site-packages (from cffi->-r requirements.txt (line 5)) (2.20)
2020-08-21T13:49:18.405766+00:00 app[worker.1]: Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in ./.heroku/python/lib/python3.8/site-packages (from aiohttp<3.7.0,>=3.6.0->discord.py[voice]>=1.4.0->-r requirements.txt (line 1)) (3.0.1)
2020-08-21T13:49:18.409496+00:00 app[worker.1]: Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in ./.heroku/python/lib/python3.8/site-packages (from aiohttp<3.7.0,>=3.6.0->discord.py[voice]>=1.4.0->-r requirements.txt (line 1)) (20.1.0)
2020-08-21T13:49:18.454054+00:00 app[worker.1]: Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in ./.heroku/python/lib/python3.8/site-packages (from aiohttp<3.7.0,>=3.6.0->discord.py[voice]>=1.4.0->-r requirements.txt (line 1)) (1.5.1)
2020-08-21T13:49:18.464060+00:00 app[worker.1]: Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.5 in ./.heroku/python/lib/python3.8/site-packages (from aiohttp<3.7.0,>=3.6.0->discord.py[voice]>=1.4.0->-r requirements.txt (line 1)) (4.7.6)
2020-08-21T13:49:18.466895+00:00 app[worker.1]: Requirement already satisfied, skipping upgrade: six in ./.heroku/python/lib/python3.8/site-packages (from PyNaCl==1.3.0; extra == "voice"->discord.py[voice]>=1.4.0->-r requirements.txt (line 1)) (1.15.0)
2020-08-21T13:49:18.468924+00:00 app[worker.1]: Requirement already satisfied, skipping upgrade: idna>=2.0 in ./.heroku/python/lib/python3.8/site-packages (from yarl<2.0,>=1.0->aiohttp<3.7.0,>=3.6.0->discord.py[voice]>=1.4.0->-r requirements.txt (line 1)) (2.10)
2020-08-21T13:49:18.546205+00:00 app[worker.1]: Installing collected packages: pip
2020-08-21T13:49:18.546659+00:00 app[worker.1]:   Attempting uninstall: pip
2020-08-21T13:49:18.547481+00:00 app[worker.1]:     Found existing installation: pip 20.1.1
2020-08-21T13:49:18.996588+00:00 app[worker.1]:     Uninstalling pip-20.1.1:
2020-08-21T13:49:19.018812+00:00 app[worker.1]:       Successfully uninstalled pip-20.1.1
2020-08-21T13:49:22.620560+00:00 app[worker.1]: Successfully installed pip-20.2.2
2020-08-21T13:49:22.878262+00:00 app[worker.1]: 
2020-08-21T13:49:22.878518+00:00 app[worker.1]: [INFO] launcher: Ok lets hope it worked
2020-08-21T13:49:22.878626+00:00 app[worker.1]: 
2020-08-21T13:49:22.879783+00:00 app[worker.1]: 
2020-08-21T13:49:22.879843+00:00 app[worker.1]: [INFO] launcher: All done.
2020-08-21T13:49:23.047323+00:00 heroku[worker.1]: Process exited with status 0
2020-08-21T13:49:23.091172+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by codeinteger6** [comment]
Gonna close this, if you still face problems you may reopen this issue.

**Comment by Kedoichi** [comment]
Sorry for the late reply
I still have that problem
I can host it in my PC but t have the problem when I use heroku to hosting it

**Comment by codeinteger6** [comment]
Please delete the Heroku app and deploy it again. I have tested it and it's working fine for me. If it still doesn't work please provide the logs so I can take a look.

**Comment by Kedoichi** [comment]
It works now many thanks sir
